name: Validate

on:
  pull_request:
    branches:
      - master

jobs:
  build-smoke-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: ${{ matrix.ghc }}-${{ matrix.deb }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.1']
        deb: ['buster']
        include:
          - ghc: '8.10.7'
            ghc_minor: '8.10'
          - ghc: '9.0.2'
            ghc_minor: '9.0'
          - ghc: '9.2.1'
            ghc_minor: '9.2'
    steps:
      - uses: actions/checkout@v2
      - name: build + smoke test [${{ matrix.ghc }}]
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 8
          max_attempts: 3
          command: |
            docker build --pull \
              -t haskell:${{ matrix.ghc }}-${{ matrix.deb }} \
              ${{ matrix.ghc_minor }}/${{ matrix.deb }}
      - uses: actions/checkout@v2
        with:
          repository: docker-library/official-images
          path: official-images
      - name: run official-images tests
        run: ./official-images/test/run.sh haskell:${{ matrix.ghc }}-${{ matrix.deb }}

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        recursive: true
